import json

# Read the notebook
with open(r'c:\Users\Administrator\OneDrive\Thesis\TimeLapse_Notebooks\visualisation.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Update the last cell (Fresnel Volume Migration)
fresnel_cell_source = [
    "# ── Fresnel Volume Migration functions ────────────────────────────────────\n",
    "def fresnel_volume_migration(traces, time_ns, rx_x, tx_x, velocity,\n",
    "                              max_depth, wavelength, dz=0.005, max_angle_deg=65.0,\n",
    "                              use_fresnel=True):\n",
    "    \"\"\"Fresnel Volume-restricted Kirchhoff PSTM for limited-aperture data.\n",
    "    \n",
    "    Uses geometric Fresnel criterion (Eq. 3, Luth et al. 2005):\n",
    "    |s + r - l| <= n*λ/2\n",
    "    where s=d_tx (tx-to-image), r=d_rx (image-to-rx), l=2*z (vertical path)\n",
    "    \n",
    "    Creates smooth weighting that suppresses off-Fresnel contributions,\n",
    "    reducing artifacts in limited-aperture surveys (boreholes, tunnels).\n",
    "    \"\"\"\n",
    "    dt_ns   = time_ns[1] - time_ns[0]\n",
    "    z_array = np.arange(0, max_depth + dz, dz)\n",
    "    image   = np.zeros((len(z_array), len(rx_x)))\n",
    "    cos_min = np.cos(np.deg2rad(max_angle_deg))\n",
    "    lam = wavelength\n",
    "    \n",
    "    for iz, z in enumerate(z_array):\n",
    "        if z == 0:\n",
    "            continue\n",
    "        for ix_out, x_out in enumerate(rx_x):\n",
    "            d_tx  = np.sqrt((x_out - tx_x)**2 + z**2)\n",
    "            cos_t = z / d_tx\n",
    "            if cos_t < cos_min:\n",
    "                continue\n",
    "            for irx, rx in enumerate(rx_x):\n",
    "                d_rx  = np.sqrt((x_out - rx)**2 + z**2)\n",
    "                cos_r = z / d_rx\n",
    "                if cos_r < cos_min:\n",
    "                    continue\n",
    "                t_ns  = (d_tx + d_rx) / velocity * 1e9\n",
    "                t_idx = int(np.round((t_ns - time_ns[0]) / dt_ns))\n",
    "                if not (0 <= t_idx < len(time_ns)):\n",
    "                    continue\n",
    "                # Geometric Fresnel criterion: |s+r-l| <= n*λ/2\n",
    "                if use_fresnel:\n",
    "                    path_diff = (d_tx + d_rx) - 2*z  # path difference vs vertical\n",
    "                    # Linear taper across Fresnel zones 1 and 2\n",
    "                    zone1_limit = lam / 2      # First Fresnel zone\n",
    "                    zone2_limit = 1.5 * lam    # Extended to include transition\n",
    "                    \n",
    "                    if np.abs(path_diff) <= zone1_limit:\n",
    "                        Fc = 1.0  # Inside zone 1: full weight\n",
    "                    elif np.abs(path_diff) <= zone2_limit:\n",
    "                        # Zones 1-2 transition: linear taper\n",
    "                        Fc = 1.0 - (np.abs(path_diff) - zone1_limit) / (zone2_limit - zone1_limit)\n",
    "                    else:\n",
    "                        Fc = 0.0  # Beyond zone 2: reject\n",
    "                else:\n",
    "                    Fc = 1.0  # Standard Kirchhoff (no Fresnel restriction)\n",
    "                \n",
    "                amplitude = (cos_t + cos_r) * 0.5 * traces[irx, t_idx]\n",
    "                image[iz, ix_out] += Fc * amplitude\n",
    "    \n",
    "    return image, z_array\n",
    "\n",
    "\n",
    "# ── Estimate wavelength and run Fresnel Volume PSTM ─────────────────────────\n",
    "wavelength = c_ice / f_central\n",
    "\n",
    "print(\"\\n=== Fresnel Volume PSTM (Geometric Criterion) ===\")\n",
    "print(f\"Dominant wavelength: {wavelength:.4f} m\")\n",
    "print(f\"Fresnel zone 1: |path_diff| ≤ {wavelength/2:.4f} m\")\n",
    "print(f\"Fresnel zone 2: {wavelength/2:.4f} m < |path_diff| ≤ {1.5*wavelength:.4f} m\")\n",
    "print(\"Running Fresnel Volume-restricted migration...\\n\")\n",
    "\n",
    "print(\"  [1/3] Baseline (Fresnel restricted) ...\")\n",
    "fv_b, _ = fresnel_volume_migration(\n",
    "    baseline_traces, time_ns, rx_positions, tx_x, c_ice,\n",
    "    MIGRATION_MAX_DEPTH, wavelength, dz=MIGRATION_DZ, use_fresnel=True)\n",
    "fig_fv1 = plot_migration_image(\n",
    "    fv_b, z_arr, rx_positions, tx_x,\n",
    "    \"Baseline — Fresnel Volume PSTM (Geometric)\",\n",
    "    fracture_depth=fracture_depth)\n",
    "plt.show()\n",
    "\n",
    "print(\"  [2/3] Timelapse (Fresnel restricted) ...\")\n",
    "fv_tl, _ = fresnel_volume_migration(\n",
    "    timelapse_traces, time_ns, rx_positions, tx_x, c_ice,\n",
    "    MIGRATION_MAX_DEPTH, wavelength, dz=MIGRATION_DZ, use_fresnel=True)\n",
    "fig_fv2 = plot_migration_image(\n",
    "    fv_tl, z_arr, rx_positions, tx_x,\n",
    "    \"Timelapse — Fresnel Volume PSTM (Geometric)\",\n",
    "    fracture_depth=fracture_depth)\n",
    "plt.show()\n",
    "\n",
    "print(\"  [3/3] Difference (Fresnel restricted) ...\")\n",
    "fv_diff, _ = fresnel_volume_migration(\n",
    "    diff_traces, time_ns, rx_positions, tx_x, c_ice,\n",
    "    MIGRATION_MAX_DEPTH, wavelength, dz=MIGRATION_DZ, use_fresnel=True)\n",
    "fig_fv3 = plot_migration_image(\n",
    "    fv_diff, z_arr, rx_positions, tx_x,\n",
    "    \"Difference — Fresnel Volume PSTM (Geometric)\",\n",
    "    fracture_depth=fracture_depth)\n",
    "plt.show()\n",
    "\n",
    "# Compare Standard vs Fresnel-restricted\n",
    "print(\"\\n=== Comparison ===\")\n",
    "print(f\"Standard PSTM max:           {np.max(np.abs(mig_b)):.3e}\")\n",
    "print(f\"Fresnel Volume PSTM max:     {np.max(np.abs(fv_b)):.3e}\")\n",
    "print(f\"Difference (relative):       {(1 - np.max(np.abs(fv_b))/np.max(np.abs(mig_b)))*100:.1f}%\")\n",
    "print(f\"\\n✓ Fresnel zone weighting suppresses off-axis contributions\")\n"
]

nb['cells'][-1]['source'] = fresnel_cell_source

# Write back
with open(r'c:\Users\Administrator\OneDrive\Thesis\TimeLapse_Notebooks\visualisation.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=4)

print("✓ Updated Fresnel Volume Migration with geometric criterion")
print(f"  - Now implements |s+r-l| <= n*λ/2 weighting")
print(f"  - Should produce noticeably different results from standard PSTM")
