import json

nb = json.load(open('Resolution_Playground.ipynb', encoding='utf-8'))
c = nb['cells'][54]
assert c['id'] == '0efd3bfe', f"Got {c['id']}"

src = [
    "import pyvista\n",
    "\n",
    "# ── Locate 2λ snapshot files ────────────────────────────────────\n",
    "slug_2lam = slugs[0]   # '2lambda'\n",
    "snap_dir  = STUDY_ROOT / 'backprop' / slug_2lam / f'backprop_{slug_2lam}_snaps'\n",
    "\n",
    "snap_files = sorted(\n",
    "    snap_dir.glob('bp_snap*.vti'),\n",
    "    key=lambda p: int(p.stem.replace('bp_snap', ''))\n",
    ")\n",
    "print(f'Found {len(snap_files)} snapshots in {snap_dir.name}/')\n",
    "\n",
    "if not snap_files:\n",
    "    print('No snapshot files found. Run the gprMax cell above first.')\n",
    "else:\n",
    "    # ── Reconstruct snapshot times ────────────────────────────────────────\n",
    "    T_ns_bp    = n_t * dt_ns\n",
    "    t_focus_theory = T_ns_bp - t0_ns   # theoretical: T - t0, all depths cancel\n",
    "    t_start_ns = max(0.0, t_focus_theory - SNAP_WIN)\n",
    "    dt_s       = dt_ns * 1e-9\n",
    "    snap_step  = max(1, int((T_ns_bp*1e-9 - t_start_ns*1e-9) / (max(1, N_SNAP - 1) * dt_s)))\n",
    "    snap_times_ns = t_start_ns + np.arange(len(snap_files)) * snap_step * dt_ns\n",
    "\n",
    "    print(f'Theoretical focus : T - t0 = {T_ns_bp:.2f} - {t0_ns:.3f} = {t_focus_theory:.3f} ns')\n",
    "    print(f'Snapshot window   : {snap_times_ns[0]:.3f} → {snap_times_ns[-1]:.3f} ns')\n",
    "    print(f'Snapshot spacing  : {snap_step * dt_ns:.4f} ns  (snap_step={snap_step})')\n",
    "\n",
    "    # ── Load |E| and Ez from every snapshot ──────────────────────────────\n",
    "    # VTI grid: 2000 x-cells × 500 y-cells × 1 z-cell\n",
    "    # mesh['E-field'] shape: (1_000_000, 3) → reshape to (ny=500, nx=2000)\n",
    "    snaps_mag = []\n",
    "    snaps_ez  = []\n",
    "    for p in snap_files:\n",
    "        mesh   = pyvista.read(str(p))\n",
    "        e_data = np.array(mesh['E-field'])                          # (n_pts, 3)\n",
    "        snaps_mag.append(np.linalg.norm(e_data, axis=1).reshape(500, 2000))\n",
    "        snaps_ez.append(e_data[:, 2].reshape(500, 2000))\n",
    "    snaps_mag = np.stack(snaps_mag)   # (n_snap, ny, nx)\n",
    "    snaps_ez  = np.stack(snaps_ez)    # (n_snap, ny, nx)\n",
    "    print(f'Loaded {len(snaps_mag)} snapshots  |  shape: {snaps_mag[0].shape}')\n",
    "\n",
    "    # ── Scatterer pixel positions ─────────────────────────────────────────\n",
    "    x1_bp = x_s1_all[0]\n",
    "    x2_bp = x_s2_all[0]\n",
    "    x_ax  = np.linspace(0, 4.0, 2000)\n",
    "    y_ax  = np.linspace(0, 1.0,  500)\n",
    "    ix1   = int(np.argmin(np.abs(x_ax - x1_bp)))\n",
    "    ix2   = int(np.argmin(np.abs(x_ax - x2_bp)))\n",
    "    iy    = int(np.argmin(np.abs(y_ax - y_scatterer)))\n",
    "    HW_X, HW_Y = 25, 8   # pixel half-window around each scatterer\n",
    "\n",
    "    # ── Empirical focus: maximise peak |E| in scatterer window ───────────\n",
    "    # Compares each snapshot's peak energy at the two scatterer locations.\n",
    "    # This is robust to any offset in t0, taper effects, or discretisation.\n",
    "    def _win_peak(snap, ix_c):\n",
    "        return snap[max(0,iy-HW_Y):iy+HW_Y+1, max(0,ix_c-HW_X):ix_c+HW_X+1].max()\n",
    "\n",
    "    focus_energy = np.array(\n",
    "        [0.5 * (_win_peak(snaps_mag[k], ix1) + _win_peak(snaps_mag[k], ix2))\n",
    "         for k in range(len(snap_files))]\n",
    "    )\n",
    "    idx_theory   = int(np.argmin(np.abs(snap_times_ns - t_focus_theory)))\n",
    "    idx_empirical = int(np.argmax(focus_energy))\n",
    "\n",
    "    print(f'\\nTheoretical focus idx : {idx_theory}   t = {snap_times_ns[idx_theory]:.3f} ns')\n",
    "    print(f'Empirical   focus idx : {idx_empirical}   t = {snap_times_ns[idx_empirical]:.3f} ns  '\n",
    "          f'(Δ = {snap_times_ns[idx_empirical] - t_focus_theory:+.3f} ns from theory)')\n",
    "\n",
    "    idx_focus = idx_empirical   # use the empirically found best frame\n",
    "    focus_mag = snaps_mag[idx_focus]\n",
    "    focus_ez  = snaps_ez[idx_focus]\n",
    "    t_actual  = snap_times_ns[idx_focus]\n",
    "\n",
    "    # ── Plot: peak energy across all snapshots ────────────────────────────\n",
    "    fig, ax = plt.subplots(figsize=(10, 3))\n",
    "    ax.plot(snap_times_ns, focus_energy, 'b.-', ms=5)\n",
    "    ax.axvline(t_focus_theory, color='gray', ls='--', lw=1.5,\n",
    "               label=f'Theory  T−t0 = {t_focus_theory:.3f} ns')\n",
    "    ax.axvline(t_actual, color='g', ls='-', lw=1.5,\n",
    "               label=f'Empirical best  = {t_actual:.3f} ns')\n",
    "    ax.set(xlabel='Simulation time [ns]', ylabel='Peak |E| at scatterers',\n",
    "           title='Focus energy vs snapshot time — 2λ dataset')\n",
    "    ax.legend(fontsize=9); ax.grid(alpha=0.3)\n",
    "    plt.tight_layout(); plt.show()\n",
    "\n",
    "    # ── Shared plot helper ────────────────────────────────────────────────\n",
    "    extent_full = [0, 4.0, 0, 1.0]\n",
    "    margin_x, margin_y = 0.4, 0.12\n",
    "\n",
    "    def _plot_pair(img, cmap, vmin, vmax, title_prefix):\n",
    "        fig, (ax_full, ax_zoom) = plt.subplots(1, 2, figsize=(14, 5))\n",
    "        for ax in (ax_full, ax_zoom):\n",
    "            ax.imshow(img, aspect='auto', cmap=cmap,\n",
    "                      vmin=vmin, vmax=vmax, extent=extent_full, origin='lower')\n",
    "            ax.plot([x1_bp, x2_bp], [y_scatterer, y_scatterer],\n",
    "                    'g*', ms=10, zorder=5, label='Scatterers')\n",
    "            ax.set(xlabel='x [m]', ylabel='y [m]')\n",
    "            ax.legend(fontsize=8)\n",
    "        ax_full.axhline(y_surface, color='cyan', lw=0.8, ls='--', label='Air-ice interface')\n",
    "        ax_full.legend(fontsize=8)\n",
    "        ax_full.set_title('Full wavefield')\n",
    "        ax_zoom.set_xlim(x1_bp - margin_x, x2_bp + margin_x)\n",
    "        ax_zoom.set_ylim(y_scatterer - margin_y, y_scatterer + margin_y)\n",
    "        ax_zoom.set_title('Zoomed — scatterer region')\n",
    "        plt.suptitle(\n",
    "            f'{title_prefix} — 2λ dataset  |  '\n",
    "            f't = {t_actual:.3f} ns  (theory {t_focus_theory:.3f} ns,  Δ = {t_actual-t_focus_theory:+.3f} ns)',\n",
    "            fontsize=11, fontweight='bold'\n",
    "        )\n",
    "        plt.tight_layout()\n",
    "        return fig\n",
    "\n",
    "    # ── Figure 1: |E| magnitude (inferno) ────────────────────────────────\n",
    "    vmax_mag = np.percentile(focus_mag, 99.5)\n",
    "    fig = _plot_pair(focus_mag, 'inferno', 0, vmax_mag, 'Back-Propagation |E|')\n",
    "    fig.savefig(snap_dir / 'backprop_focus_mag.png', dpi=150, bbox_inches='tight')\n",
    "    plt.show()\n",
    "\n",
    "    # ── Figure 2: Ez component (seismic) ─────────────────────────────────\n",
    "    vmax_ez = np.percentile(np.abs(focus_ez), 99.5)\n",
    "    fig = _plot_pair(focus_ez, 'seismic', -vmax_ez, vmax_ez, 'Back-Propagation Ez')\n",
    "    fig.savefig(snap_dir / 'backprop_focus_ez.png', dpi=150, bbox_inches='tight')\n",
    "    plt.show()\n",
]

c['source'] = src
c['outputs'] = []
c['execution_count'] = None

with open('Resolution_Playground.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f'Done. Lines: {len(src)}')
